---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
images:
  - name: bretfisher/wordsmith-api
    newTag: latest
  - name: bretfisher/wordsmith-web
    newName: ghcr.io/muir-island/wordsmith-web
    newTag: stable-20230719-efb9e4c
configMapGenerator:
  - name: db-schema
    files:
      - words.sql
